services:
  madr_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/madr_database
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  madr:
    image: madr
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - madr_database
    environment:
      DATABASE_URL: "postgresql+psycopg://app_user:app_password@madr_database:5432/app_db"

volumes:
  pgdata:
