"""alterada foreign key para romancista ao inves de autoria

Revision ID: 48e4bfdf94a2
Revises: 9d8e299ec469
Create Date: 2025-07-17 07:47:15.749319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e4bfdf94a2'
down_revision: Union[str, Sequence[str], None] = '9d8e299ec469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
