"""foreign key livro -> romancista

Revision ID: 9d8e299ec469
Revises: b33db1d39a32
Create Date: 2025-07-17 07:36:24.102405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d8e299ec469'
down_revision: Union[str, Sequence[str], None] = 'b33db1d39a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'livros', 'romancistas', ['romancista_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'livros', type_='foreignkey')
    # ### end Alembic commands ###
